// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_y2rjLn84aqTYZMmXO9xh_U2YebfLDNQ',
    appId: '1:337503751014:web:9895f4b02e6bfc7a1796a7',
    messagingSenderId: '337503751014',
    projectId: 'toff-toff',
    authDomain: 'toff-toff.firebaseapp.com',
    databaseURL: 'https://toff-toff-default-rtdb.firebaseio.com',
    storageBucket: 'toff-toff.appspot.com',
    measurementId: 'G-H1G4F8DDYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWE4EiVM77tbrdk9arXvy49D4Ygmbt_GM',
    appId: '1:337503751014:android:95e4dda4a32372701796a7',
    messagingSenderId: '337503751014',
    projectId: 'toff-toff',
    databaseURL: 'https://toff-toff-default-rtdb.firebaseio.com',
    storageBucket: 'toff-toff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjK7iMp-6yxgBwS6Wq1m9sNSz2ZDn2tQM',
    appId: '1:337503751014:ios:006f0c51b238723a1796a7',
    messagingSenderId: '337503751014',
    projectId: 'toff-toff',
    databaseURL: 'https://toff-toff-default-rtdb.firebaseio.com',
    storageBucket: 'toff-toff.appspot.com',
    androidClientId: '337503751014-5j7qon296le3kjdnfh3931nl3j5p9duc.apps.googleusercontent.com',
    iosClientId: '337503751014-ea8m4oqj2nh617l465h7kicjgp2v9iks.apps.googleusercontent.com',
    iosBundleId: 'com.example.ggmapFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjK7iMp-6yxgBwS6Wq1m9sNSz2ZDn2tQM',
    appId: '1:337503751014:ios:006f0c51b238723a1796a7',
    messagingSenderId: '337503751014',
    projectId: 'toff-toff',
    databaseURL: 'https://toff-toff-default-rtdb.firebaseio.com',
    storageBucket: 'toff-toff.appspot.com',
    androidClientId: '337503751014-5j7qon296le3kjdnfh3931nl3j5p9duc.apps.googleusercontent.com',
    iosClientId: '337503751014-ea8m4oqj2nh617l465h7kicjgp2v9iks.apps.googleusercontent.com',
    iosBundleId: 'com.example.ggmapFlutter',
  );
}
